gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    user_provider: security.user.provider.concrete.app_user_provider
    ttl: 604800 # 7 jours
    firewall: api
    single_use: true

  
