services:
  php:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./back:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - backend

  mysql:
    image: mysql:8
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      - mysql
    networks:
      - backend
  node:
    build:
      context: ./front
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: react
    ports:
      - "5173:5173"
 

volumes:
  db_data:

networks:
  backend:
